### ISSUE TITLE
V2 - None of the icons are displaying

### ISSUE THREAD

**Issue by ProtectedVoid** [LucaFontanot/dbd-skillcheck-simulator#3]
![image](https://github.com/LucaFontanot/dbd-skillcheck-simulator/assets/58258132/1ee5d7a7-6188-4101-8721-29c69a5b7f6b)

In the effect and in the perk menu, none of the icons are displaying. They instead show that default picture.

To reproduce, simply open either the effect or the perk menu.

**Comment by LucaFontanot** [comment]
Thanks for the feedback. Apparently this issue came only on the compiled version and not on the development one. In the following days i will work again on this project :+1:

**Comment by LucaFontanot** [comment]
Fixed in latest release
