### ISSUE TITLE
remove fade-in animation when skillchecks appear

### ISSUE THREAD

**Issue by semplar** [LucaFontanot/dbd-skillcheck-simulator#6]
this feels unnatural, different from the game and is actually makes hitting skillchecks more challenging because it's harder to read visual information when it's partially transparent, but it's essential to have it asap

**Comment by LucaFontanot** [comment]
Thanks for the feedback. I did not think about this, you are right. In the following days i will work again on this project :+1:

**Comment by LucaFontanot** [comment]
Fixed in latest release
